export const logos = [
  // { src: "/logos/google.svg", alt: "Google" },
  // { src: "/logos/microsoft.svg", alt: "Microsoft" },
  // { src: "/logos/amazon.svg", alt: "Amazon" },
  { src: "/logos/netflix.svg", alt: "Netflix" },
  { src: "/logos/apple.svg", alt: "Apple" },
  { src: "/logos/phonepe_logo.svg", alt: "Phonepay" },
  { src: "/logos/meta.svg", alt: "Meta" },
  { src: "/logos/aws_logo.svg", alt: "Aws" },
  { src: "/logos/phonepe_logo.svg", alt: "Phonepay" },
  { src: "/logos/netflix.svg", alt: "Netflix" },
  { src: "/logos/apple.svg", alt: "Apple" },
  { src: "/logos/phonepe_logo.svg", alt: "Phonepay" },
  { src: "/logos/meta.svg", alt: "Meta" },
  { src: "/logos/aws_logo.svg", alt: "Aws" },
  { src: "/logos/phonepe_logo.svg", alt: "Phonepay" },
];
